[package]

name = "rust-ffi-glfw"
version = "0.0.2"
authors = [ "Fedor Rusak <node@fedor-rusak.ru>" ]

[dependencies]
render_lib= "0.1.3"
libc = "0.2.23"

[patch.crates-io]
render_lib = { git = "https://github.com/fedor-rusak/render_lib", branch="vulcano" }